export const REQUEST_POSTS_STARTED = "REQUEST_POSTS_STARTED";
export const REQUEST_POSTS_SUCCEEDED = "REQUEST_POSTS_SUCCEEDED";
export const REQUEST_POSTS_FAILED = "REQUEST_POSTS_FAILED";

export const ADD_READ_LATER = "ADD_READ_LATER";
export const REMOVE_READ_LATER = "REMOVE_READ_LATER";
